version: '3'

services:
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8080
    volumes:
      - .:/kios
    ports:
      - "8080:8080"

  db:
    container_name: kiosDB
    image: postgres:11
    restart: always
    environment:
      POSTGRES_DB: kios
      POSTGRES_USER: idris
      POSTGRES_PASSWORD: idrisaja
    ports:
      - "6543:6543"
    volumes:
      - ./db-kios:/var/lib/postgresql/data/

  pgadmin:
    container_name: kiosPgadmin
    image: dpage/pgadmin4:latest
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: kios@mail.com
      PGADMIN_DEFAULT_PASSWORD: SuperSecret
      PGADMIN_LISTEN_PORT: '8090'
    ports:
      - "8090:8090"