version: '3'

services:
  db:
    container_name: kiosDB
    image: postgres:11
    restart: always
    environment:
      POSTGRES_DB: kios
      POSTGRES_USER: idris
      POSTGRES_PASSWORD: idrisaja
      POSTGRES_LISTEN_PORT: '5432'
    ports:
      - "5432:5432"
    volumes:
      # - /var/lib/pgsql/11/data:/var/lib/postgresql/data/
      - ./db-kios:/var/lib/postgresql/data/
    networks:
      net-core:
        ipv4_address: 172.18.0.3

  pgadmin:
    container_name: kiosPgadmin
    image: dpage/pgadmin4:latest
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: kios@mail.com
      PGADMIN_DEFAULT_PASSWORD: SuperSecret
      PGADMIN_LISTEN_PORT: '8090'
    ports:
      - "8090:8090"
    networks:
      net-core:
        ipv4_address: 172.18.0.4

  redis:
    container_name: redis_kios
    image: redis:6
    command: redis-server /redis/redis.conf
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - ./redis/redis.conf:/redis/redis.conf
    networks:
      net-core:
        ipv4_address: 172.18.0.5

  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8080
    volumes:
      - .:/kios
    ports:
      - "8080:8080"
    networks:
      net-core:
        ipv4_address: 172.18.0.2
    depends_on:
      - redis
      - db

networks:
  net-core:
    ipam:
      driver: default
      config:
        - subnet: 172.18.0.0/16
