version: '3'

services:
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8080
    volumes:
      - .:/kios
    ports:
      - "8080:8080"

  db:
    container_name: kiosDB
    image: postgres:11
    restart: always
    environment:
      POSTGRES_DB: kios
      POSTGRES_USER: idris
      POSTGRES_PASSWORD: idrisaja
    ports:
      - "6543:6543"
    volumes:
      - /var/lib/postgresql/data
