# Generated by Django 3.0.7 on 2020-08-24 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20200713_1353'),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('city', models.CharField(max_length=256)),
                ('city_ascii', models.CharField(max_length=256)),
                ('lat', models.CharField(max_length=256)),
                ('lng', models.CharField(max_length=256)),
                ('country', models.CharField(max_length=256)),
                ('iso2', models.CharField(max_length=2)),
                ('iso3', models.CharField(max_length=3)),
                ('admin_name', models.CharField(max_length=256)),
                ('capital', models.CharField(max_length=64)),
                ('population', models.CharField(max_length=256)),
            ],
        ),
    ]
