# Generated by Django 3.0.7 on 2020-07-15 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_add_location'),
    ]

    operations = [
        migrations.CreateModel(
            name='Personil',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=512)),
                ('last_name', models.CharField(max_length=512)),
                ('company_name', models.CharField(max_length=512)),
                ('address', models.CharField(max_length=512)),
                ('city', models.CharField(max_length=512)),
                ('county', models.CharField(max_length=512)),
                ('state', models.CharField(max_length=512)),
                ('zip', models.IntegerField(max_length=10)),
                ('phone1', models.CharField(max_length=512)),
                ('phone2', models.CharField(max_length=512)),
                ('email', models.EmailField(max_length=254)),
                ('web', models.CharField(max_length=512)),
            ],
        ),
    ]
