# Generated by Django 3.0.7 on 2020-08-26 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_location'),
    ]

    operations = [
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('country', models.CharField(max_length=128)),
                ('currency', models.CharField(max_length=128)),
                ('code', models.CharField(max_length=128)),
                ('symbol', models.CharField(max_length=128)),
            ],
        ),
    ]
