# Generated by Django 3.0.7 on 2020-07-22 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_add_personil'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personil',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
