# Generated by Django 3.0.7 on 2020-08-28 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_currency'),
    ]

    operations = [
        migrations.CreateModel(
            name='USA',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=64)),
                ('last_name', models.CharField(max_length=64)),
                ('company_name', models.CharField(max_length=128)),
                ('address', models.CharField(max_length=128)),
                ('city', models.CharField(max_length=64)),
                ('country', models.CharField(max_length=64)),
                ('state', models.CharField(max_length=8)),
                ('zip', models.CharField(max_length=8)),
                ('phone1', models.CharField(max_length=32)),
                ('phone2', models.CharField(max_length=32)),
                ('email', models.EmailField(max_length=64)),
                ('web', models.URLField()),
            ],
        ),
    ]
