# Generated by Django 3.0.7 on 2020-08-05 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_add_model_citie'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personil',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
